## Real State- PRICE PREDICTOR

In [5]:
import pandas as pd

housing_df=pd.read_csv("data.csv")
housing_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469    NaN  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
housing_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       502 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [7]:
housing_df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  502.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.283576   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704100   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.884250   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [8]:
housing_df["CHAS"].value_counts()

CHAS
0    471
1     35
Name: count, dtype: int64

In [9]:
# for histogram
# housing_df.hist(bins=50,figsize=(20,15))

## TRAIN-TEST SPLITTING

In [10]:
# FOR PRACTICE SAME THING HAVE IN SKLEARN

import numpy as np

def train_test_split(data,test_size):
    np.random.seed(42)   #----> Generates (fixed)pseudo-random number based on seed. Seed can be any number.
    suffled=np.random.permutation(len(data))#---->Randomly permute a sequence, or return a permuted range.
    print(suffled)
    test_set_size=int(len(data)*test_size)
    test_indices=suffled[:test_set_size]
    train_indices=suffled[test_set_size:]
    return data.iloc[test_indices],data.iloc[train_indices]  #-->iloc[Integer-based Indexing] and loc[(Label-based Indexing)]
train_set,test_set=train_test_split(housing_df,0.2)

[173 274 491  72 452  76 316 140 471 500 218   9 414  78 323 473 124 388
 195 448 271 278  30 501 421 474  79 454 210 497 172 320 375 362 467 153
   2 336 208  73 496 307 204  68  90 390  33  70 470   0  11 281  22 101
 268 485 442 290  84 245  63  55 229  18 351 209 395  82  39 456  46 481
 444 355  77 398 104 203 381 489  69 408 255 392 312 234 460 324  93 137
 176 417 131 346 365 132 371 412 436 411  86  75 477  15 332 423  19 325
 335  56 437 409 334 181 227 434 180  25 493 238 244 250 418 117  42 322
 347 182 155 280 126 329  31 113 148 432 338  57 194  24  17 298  66 211
 404  94 154 441  23 225 433 447   5 116  45  16 468 360   3 405 185  60
 110 321 265  29 262 478  26   7 492 108  37 157 472 118 114 175 192 272
 144 373 383 356 277 220 450 141 369  67 361 168 499 394 400 193 249 109
 420 145  92 152 222 304  83 248 165 163 199 231  74 311 455 253 119 284
 302 483 357 403 228 261 237 386 476  36 196 139 368 247 287 378  59 111
  89 266   6 364 503 341 158 150 177 397 184 318  1

In [11]:
#print(f"rows in train_set {len(train_set)} \nrows in test_set {len(test_set)}")

In [12]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(housing_df, test_size=0.2, random_state=42)
print(f"rows in train_set {len(train_set)} \nrows in test_set {len(test_set)}")

rows in train_set 404 
rows in test_set 102


In [13]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index,test_index in split.split(housing_df,housing_df["CHAS"]):
    strat_train_set=housing_df.loc[train_index]
    strat_test_set=housing_df.loc[test_index]


In [14]:
#strat_test_set["CHAS"].value_counts()

In [15]:
#95/7

In [16]:
#strat_train_set["CHAS"].value_counts()

In [17]:
#376/28

In [18]:
housing_df= strat_train_set.copy()

## LOOKING FOR CORRELATIONS

In [19]:
corr_matrix=housing_df.corr()
corr_matrix["MEDV"].sort_values(ascending=False)   # pearsion correlation--how much proportion[- or +]

MEDV       1.000000
RM         0.679510
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [20]:
# from pandas.plotting import scatter_matrix
# attributes=["MEDV","RM","ZN","LSTAT"]
# scatter_matrix(housing_df[attributes],figsize=(12,8))

In [21]:
# housing_df.plot(kind="scatter",x="RM",y="MEDV",alpha=0.8)

## TRYING OUT ATTRIBUTE COMBINATION

In [22]:
housing_df["TAXRM"]=housing_df["TAX"]/housing_df["RM"]
housing_df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
254  0.04819  80.0   3.64     0  0.392  6.108  32.0  9.2203    1  315   
348  0.01501  80.0   2.01     0  0.435  6.635  29.7  8.3440    4  280   
476  4.87141   0.0  18.10     0  0.614  6.484  93.6  2.3053   24  666   
321  0.18159   0.0   7.38     0  0.493  6.376  54.3  4.5404    5  287   
326  0.30347   0.0   7.38     0  0.493  6.312  28.9  5.4159    5  287   

     PTRATIO       B  LSTAT  MEDV       TAXRM  
254     16.4  392.89   6.57  21.9   51.571709  
348     17.0  390.94   5.99  24.5   42.200452  
476     20.2  396.21  18.68  16.7  102.714374  
321     19.6  396.90   6.87  23.1   45.012547  
326     19.6  396.90   6.15  23.0   45.468948

In [23]:
# housing_df.plot(kind="scatter",x="TAXRM",y="MEDV",alpha=0.8)

In [24]:
housing_df=strat_train_set.drop("MEDV",axis=1)
housing_labels=strat_train_set["MEDV"].copy()

## MISSING ATTRIBUTES

In [25]:
# To take care of missing attributes, we have have three options:

# 1.get rid of the  missing data points [dropna]
# 2. get rid of the whole attribute  [drop]
# 3. set the value to the same (0,mean or median)  [fillna]
# total shape (506, 15)
# original data is not change until we get inplace=True

In [26]:
# option 1 [4 values deleted]

a=housing_df.dropna(subset=["RM"]).shape
a

(400, 13)

In [27]:
# option 2 [1 coloumn deleted]

b=housing_df.drop("RM",axis=1)
b.shape

(404, 12)

In [28]:
# option 3 [at missing data place replace with median]

median=housing_df["RM"].median()   #compute median for option 3 [6.2085]
housing_df["RM"].fillna(median) 

254    6.108
348    6.635
476    6.484
321    6.376
326    6.312
       ...  
155    6.152
423    6.103
98     7.820
455    6.525
216    5.888
Name: RM, Length: 404, dtype: float64

In [29]:
housing_df.shape

(404, 13)

In [30]:
housing_df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.278532   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.714911   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.877250   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [31]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="median")
imputer.fit(housing_df)

SimpleImputer(strategy='median')

In [32]:
imputer.statistics_   # compute median for each coloumn

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21000e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [33]:
x=imputer.transform(housing_df)

In [34]:
housing_tr=pd.DataFrame(x,columns=housing_df.columns)

In [35]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.277854   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.711387   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

## Scikit-learn Design

PRIMARILY , THREE TYPE OF OBJECTS

1.ESTOMATOR - it estimate some parameter based on a dataset. Eg. Imputer. It has a fit method and transform method. Fit method - Fits the dataset and calculates internal parameters.

2.TRANSFORMERS - transform method takes input and returns output based on the learning from fit(). It also has a convenience function called fit_ transform() which fits and then transforms.

3.PREDICTORS - LinearRegression model is an example of predictor. fit() and predict() are two common functions. it also give score() function which will evaluate the predictions.

## feature scaling

PRIMARILY 2 TYPE FEATURE SCALING:

1.MIN-MAX SCALING (NORMALIZATION) = (value - min)/(max - min)
sklearn provide a class [MinMaxScaler]

2.STANDARDIZATION = (value - mean)/(std)
sklearn provides a class [StandardScaler]

## CREATING A PIPELINE

In [36]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline=Pipeline([('imputer',SimpleImputer(strategy="median")),
                      # ....add as many as you want in your pipeline
                      ('std_scaler',StandardScaler()), ])

In [37]:
housing_num_tr=my_pipeline.fit_transform(housing_df)
housing_num_tr   # numpy array
housing_num_tr.shape

(404, 13)

## SELECTING A DESIRE MODEL FOR DRAGON REAL ESTATES

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
# model=LinearRegression()
# model=DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

RandomForestRegressor()

In [39]:
some_data=housing_df.iloc[:5]
some_labels=housing_labels.iloc[:5]
prepared_data=my_pipeline.transform(some_data)
model.predict(prepared_data)

array([22.219, 25.352, 16.387, 23.399, 23.671])

In [40]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

## EVALUATING THE MODEL

In [41]:
from sklearn.metrics import mean_squared_error
housing_predictions=model.predict(housing_num_tr)
mse=mean_squared_error(housing_labels,housing_predictions)
rmse=np.sqrt(mse)

In [42]:
rmse

np.float64(1.1513387708865424)

## USING BETTER EVALUATION TECHNIQUE - CROSS VALIDATION

In [43]:
# 1 2 3 4 5 6 7 8 9 
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model, housing_num_tr,housing_labels,scoring="neg_mean_squared_error", cv=10)
rmse_scores=np.sqrt(-scores)

In [44]:
rmse_scores  

array([2.89483346, 2.77397716, 4.46712866, 2.57468839, 3.27784209,
       2.47384895, 4.41972758, 3.58395867, 2.94740644, 3.45580564])

In [45]:
def print_scores(scores):
    print("scores",scores)
    print("mean",scores.mean())
    print("standard deviation",scores.std())

In [46]:
print_scores(rmse_scores)

scores [2.89483346 2.77397716 4.46712866 2.57468839 3.27784209 2.47384895
 4.41972758 3.58395867 2.94740644 3.45580564]
mean 3.2869217042569305
standard deviation 0.6703321774564384


## SAVING THE MODEL

In [47]:
from joblib import dump, load
dump(model,'Dragon.joblib')

['Dragon.joblib']

## Testing the model on test data

In [48]:
x_test=strat_test_set.drop("MEDV",axis=1)
y_test=strat_test_set["MEDV"].copy()
x_test_prepared=my_pipeline.transform(x_test)
final_prediction=model.predict(x_test_prepared)
final_mse=mean_squared_error(y_test,final_prediction)
final_rmse=np.sqrt(final_mse)
#print(final_prediction,list(y_test))

In [49]:
final_rmse

np.float64(2.904193121380619)

In [50]:
prepared_data[0]

array([-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23906061, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034])

In [51]:
from joblib import dump, load
import numpy as np
model=load('Dragon.joblib')
input=np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.23906061, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
model.predict(input)

array([22.219])